### ISSUE TITLE
Auto Search for Lynda SQL DB produces wrong location

### ISSUE THREAD

**Issue by jzastoupil** [medos20/LyndaVisualDecryptor#1]
Auto Search for Lynda SQL DB produces wrong location. It is assuming that my sql db is in a location that doesn't exist.

**Comment by medos20** [comment]
Thank you for testing my software,did you install Lynda Desktop App first (only Lynda desktop for windows 7+)  ? if you did, so its assumed that your db.sqlite location are in the location like : "C:\Users\yourUserName\AppData\Local\lynda.com\Lynda.com Desktop App\db.sqlite"
which (yourUserName is the userName of your machine"

also if you already installed the lynda desktop app win7+ version you can skip this step

**Comment by jzastoupil** [comment]
Yes I installed Lynda Desktop (on Win 10) first, and my db location is not what is assumed - it is actually at C:\Users\<user>\AppData\Local\Packages\lynda.com.lynda.com_0dmhem0sv94sr\LocalState\db.sqlite

**Comment by medos20** [comment]
So Strange! , this is first time to see this Path (C:\Users<user>\AppData\Local\Packages\lynda.com.lynda.com_0dmhem0sv94sr\LocalState\db.sqlite) but did you use Win7+ Version ?, also I can add real search method to find (db.sqlite) i already added in my beta test but the problem it took about 3 minutes to get the REAL path Instead of the ASSUMED path, so i'm afraid the User Will feel bored from Waiting, maybe i should make a Precedence Procedure before entering the Main Screen to test the location of the (db.sqlite), so if you are sure that you used Win7+ version not Win8.1+ version so let me know so i can make special version to make real search for the database no matter it will take some time!, and thank you for testing the software i hope you enjoyed it.

**Comment by jzastoupil** [comment]
I installed Lynda from the Windows 10 app store , it says it is version 1.6.2.11

**Comment by medos20** [comment]
ahh. this the Problem. because i told you that its only work with the Win 7+, you can download from :
https://www.lynda.com/apps/desktop-app
and Select the Black Icon in the Right Down of the Page (you will see (Windows 7+
) under the ICON, so first you need to Uninstall the current version, I Mention that in the Help PDF File in Page 2 -  but i need to know if you manually copy the (db.sqlite) database file to specific folder? did you succeeded in Decrypting Video Course? Because if its Really work in that version i have to change the code to make real search on the real path even if it take some time, thanks a lot for your deep test

**Comment by medos20** [comment]
but i need to know if you manually copy the (db.sqlite) database file to specific folder? did you succeeded in Decrypting Video Course?

**Comment by jzastoupil** [comment]
I did not manually copy the file - what I actually ended up doing is creating the batch script and then manually editing the location there and using the batch script to download. It works well :)

**Comment by medos20** [comment]
Great, this mean i will cancel the assumed script and replace it with real searching script for the real path, thank you very much

**Comment by medos20** [comment]
Lynda Visual Decryptor V2.0 Release!, Download From Here 

https://github.com/medos20/LyndaVisualDecryptor/releases/download/v2.0/lyndavisualDecryptor_v2.0.zip

What’s New in Version 2.0  :
============================
1-Now the Software Support Real Search for the Database File Instead of Assumed Search Path So that make the Software compatible with Most of Lynda Desktop App Versions.
2-Now The Manual Search Support the Hidden File and Folders Automatically.
3-Now you Can Decrypt One File Only to Test your Files Before Make Big Decryption of the Folder.
