### ISSUE TITLE
Manual Search for SQL Db doesnt show hidden folders

### ISSUE THREAD

**Issue by jzastoupil** [medos20/LyndaVisualDecryptor#2]
I am unable to manually search for the SQL database because the tree doesn't show the AppData folder (which is a hidden folder)

**Comment by medos20** [comment]
Thank you for testing my software, Yes you are Right, i will try to fix that in the next version, but you can search for the (db.sqlite) manually and copy to new location right now.

also if you already installed the lynda desktop app win7+ version you can skip this step
both of manual and auto search are optional, you can continue use the software without them if you already installed lynda desktop app win7+

**Comment by jzastoupil** [comment]
Yes I was able to search and get it working, I just wanted you to be aware of the issue

**Comment by medos20** [comment]
The Problem is FIXED, thanks to god and the Software is able to Let the User Select the Database file from any Hidden Path,  i Will finish my Tests Before Launching the Next Release.

**Comment by medos20** [comment]
Lynda Visual Decryptor V2.0 Release!, Download From Here

https://github.com/medos20/LyndaVisualDecryptor/releases/download/v2.0/lyndavisualDecryptor_v2.0.zip

What’s New in Version 2.0 :
1-Now the Software Support Real Search for the Database File Instead of Assumed Search Path So that make the Software compatible with Most of Lynda Desktop App Versions.
2-Now The Manual Search Support the Hidden File and Folders Automatically.
3-Now you Can Decrypt One File Only to Test your Files Before Make Big Decryption of the Folder.
